pipeline {
    agent any 
    stages{
        stage('BUILD') {
            steps{
                 sh '''
                    sleep 5
                    echo "This is a BUILD stage"
                '''
            }
        }
        stage('Deleviry') {
            steps{
                 sh '''
                    sleep 5
                    echo "This is a Delivery stage"
                '''
            }
        }
        
        stage('Test') {
            steps{
                sh '''
                    sleep 6
                    echo "This is a TEST stage"
                '''
            }
        }
        stage('Processing') {
            steps{
                 sh '''
                    sleep 5
                    echo "This is a Processing stage"
                '''
            }
        }

        stage('DEPLOY') {
            steps{
                sh '''
                    sleep 5
                    echo "This is a DEPLOY stage"
                '''
            }
        }
    }
}
